version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./shared-db:/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    volumes:
      - ./shared-db:/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-html:/usr/share/nginx/html:ro  # si sirves frontend
    depends_on:
      - user-service
      - task-service
    networks:
      - backend


  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./nginx-html:/app/frontend/public:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./nginx-html:/usr/share/nginx/html:ro
    ports:
      - '88:88'
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  backend:
    driver: bridge
